name: update profile readme typingspeed

on: 
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - main
  workflow_dispatch:

jobs:

  update-readme:
    runs-on: ubuntu-latest
    container:
      image: alpine/curl:8.14.1
    steps:
      - uses: actions/checkout@v4
      - name: run script to update readme
        run: ./scripts/aa.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

